on:
  push:
    branches: main

name: Render pdfs

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
      - run: |
          quarto add quarto-journals/acs
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: pdf
          path: paper

      - uses: actions/upload-artifact@v4
        with:
          name: paper files
          path: paper
